# Maven package Java project Web App to Linux on Azure
# Build your Java project and deploy it to Azure as a Linux web app
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- master

variables:

  # Azure Resource Manager connection created during pipeline creation
  azureSubscription: '18312d63-f055-42bb-8263-75574b60a49e'
  
  # Web app name
  webAppName: 'ubi-spring-boot-sample'

  # Environment name
  environmentName: 'ubi-spring-boot-sample'
  
  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: MavenPackageAndPublishArtifacts
    displayName: Maven Package and Publish Artifacts
    pool:
      vmImage: $(vmImageName)
    
    steps:
    - task: JavaToolInstaller@1
      displayName: 'Java'
      inputs:
        versionSpec: '21'
        jdkSourceOption: 'PreInstalled'
        jdkArchitectureOption: 'x64'
    - task: Maven@4
      displayName: 'Maven Package'
      inputs:
        mavenPomFile: 'pom.xml'
    - task: AzureSpringCloud@0
      displayName: 'Spring'
      inputs:
        azureSubscription: 'Azure DevOps'
        appName: 'ubi-spring-boot-sample'
        Action: Deploy
        AzureSpringCloud: 'ubi-spring-boot-sample'        