# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureContainerApps@1
  inputs:
    appSourcePath: '$(System.DefaultWorkingDirectory)'
    azureSubscription: 'Azure DevOps'
    acrName: 'ubicontainers'
    containerAppName: 'ubi-spring-boot-sample'
    resourceGroup: 'Default-Web-NorthEurope'
    containerAppEnvironment: 'ubi-container-env'
    location: 'northeurope'
