services:
  spring-boot-sample:
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "app"
    image: "spring-boot-sample"
    container_name: "spring-boot-sample"
    ports:
      - "8080:8080"
  spring-boot-sample-azure:
    build:
      context: "."
      dockerfile: "Dockerfile"
      target: "app"
    image: "spring-boot-sample-azure"
    container_name: "spring-boot-sample-azure"
    env_file: 
      - path: "azure.env"
        required: true
    ports:
      - "80:80"
    profiles:
      - "azure"
