spring:
  security:
    oauth2:
      client:
        provider:
          ubisecure:
            issuer-uri: https://login.example.ubidemo.com/uas
        registration:
          ubisecure:
            clientId: 6864a917-74cc-40fe-914a-87b1c5522633
            clientSecret: l1gL0fNWPsh5eLX-JsBuFeGQJOdnw-2m
            scope: openid
logging:
  level:
    org.springframework: DEBUG
