spring:
  config.activate.on-profile: azure
  security.oauth2.client.provider.ubisecure:
    issuer-uri: ${OPENIDCONNECT_ISSUER:https://login.example.ubidemo.com/uas}
  security.oauth2.client.registration.ubisecure:
    clientId: ${OPENIDCONNECT_CLIENT_ID}
    clientSecret: ${OPENIDCONNECT_CLIENT_SECRET}
    scope: ${OPENIDCONNECT_SCOPE:openid}
server:
  port: 80
  tomcat:
    remote-ip-header: x-forwarded-for
    protocol-header: x-forwarded-proto
